// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnkflwxehljxihnzvgmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJua2Zsd3hlaGxqeGlobnp2Z21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDkxODgsImV4cCI6MjA1MDk4NTE4OH0.cY9DKnQ_UYS7Dsf7xhecptx3jKu5vHWs76hhL0R15pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);